server:
  port: 8090

spring:
  profiles:
    active: local

  application:
    name: optimistic-jpa-service

  # JPA 설정
  jpa:
    # entity로 테이블 생성 하고 schema.sql & data.sql 도 체크
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # H2 설정
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console

  # Datasource 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  sql:
    init:
      encoding: UTF-8
      schema-locations: classpath*:db/${database}/schema.sql
      data-locations: classpath*:db/${database}/data.sql

logging:
  level:
    org:
      hibernate:
        sql: debug
        type: trace


database: h2