server:
  port: 8090

spring:
  profiles:
    active: local

  application:
    name: optimistic-jpa-service

  # JPA 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # H2 설정
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console

  # Datasource 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

logging:
  level:
    org:
      hibernate:
        sql: debug
        type: trace

